addSbtPlugin("ch.epfl.scala"    % "sbt-scalafix"                       % "0.11.1")
addSbtPlugin("com.github.sbt"   % "sbt-github-actions"                 % "0.25.0")
addSbtPlugin("com.github.cb372" % "sbt-explicit-dependencies"          % "0.3.1")
addSbtPlugin("com.github.sbt"   % "sbt-pgp"                            % "2.2.1")
addSbtPlugin("com.timushev.sbt" % "sbt-updates"                        % "0.6.3")
addSbtPlugin("org.typelevel"    % "sbt-tpolecat"                       % "0.5.0")
addSbtPlugin("io.isomarcte"     % "sbt-version-scheme-enforcer-plugin" % "2.1.0.3")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"                       % "2.5.2")
