addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"                       % "0.9.25")
addSbtPlugin("com.codecommit"            % "sbt-github-actions"                 % "0.10.1")
addSbtPlugin("com.github.cb372"          % "sbt-explicit-dependencies"          % "0.2.16")
addSbtPlugin("com.jsuereth"              % "sbt-pgp"                            % "2.1.1")
addSbtPlugin("com.timushev.sbt"          % "sbt-updates"                        % "0.5.1")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"                       % "0.1.16")
addSbtPlugin("io.isomarcte"              % "sbt-version-scheme-enforcer-plugin" % "0.0.0.1")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"                       % "2.4.2")
